### ISSUE TITLE
Commands and syntax

### ISSUE THREAD

**Issue by konrad51** [redraw/wizmusic#1]
I am trying to use your program "wizmusic". I have Spotify client ID , client secret and redirect uri. When I try to run I get "Missing envs: {'SPOTIPY_CLIENT_ID', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_REDIRECT_URI'}. Can you give me an example of the command and syntax of running Wizmusic? I am trying wizmusic -H <wiz-ip>  then env vars. Can you give me an example with values, commas , spaces, so I can plug in my numbers? Thanks!

**Comment by redraw** [comment]
Hi, first you need to create a Spotify app in their dashboard: https://developer.spotify.com

Then setup those environment variables in your shell ('SPOTIPY_CLIENT_ID', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_REDIRECT_URI')

For example,
```bash
export SPOTIPY_CLIENT_ID=<CLIENT-ID-FROM-SPOTIFY-APP-DASHBOARD>
export SPOTIPY_CLIENT_SECRET=<CLIENT-SECRET-FROM-SPOTIFY-APP-DASHBOARD>
export SPOTIPY_REDIRECT_URI=http://localhost:9090
```

Then you can run
```bash
wizmusic
```

**Comment by redraw** [comment]
In the example above, make sure to put the same Redirect URI in the Spotify app dashboard

**Comment by konrad51** [comment]
I am confused here. I created an entry in dashboard. Got client id. Got client secret. Where I get confused is here "Then setup those environment variables in your shell ('SPOTIPY_CLIENT_ID', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_REDIRECT_URI')".  How and where do I do this? What Shell? Please give me a detailed , step by step example , if you could. Assume I know almost nothing. Also is getting the client id and client secret sufficient ( I am not creating an actual application , I am just entering my information in the dashboard.) Thank you for your patience.

**Comment by konrad51** [comment]
I am confused here. I created an entry in dashboard. Got client id. Got client secret. Where I get confused is here "Then setup those environment variables in your shell ('SPOTIPY_CLIENT_ID', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_REDIRECT_URI')". How and where do I do this? What Shell? Please give me a detailed , step by step example , if you could. Assume I know almost nothing. Also is getting the client id and client secret sufficient ( I am not creating an actual application , I am just entering my information in the dashboard.) Thank you for your patience.

**Comment by konrad51** [comment]
Still trying to get this to work. Using windows 10. am using...  powershell $Env:SPOTIPY_CLIENT_ID='7644a895f19b4a9d8d97b9738b899476' Same with client secret and redirect uri. This is what I get "C:\Users\schultz\AppData\Local\Programs\Python\Python39\Scripts>wizmusic
Missing envs: {'SPOTIPY_REDIRECT_URI', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_CLIENT_ID'}. Please help .Thank you.

**Comment by redraw** [comment]
Never used powershell but you can verify your envs running
```
Get-ChildItem Env:
```

**Comment by redraw** [comment]
Envs might not be reaching the child process (wizmusic), try this

```
set SPOTIPY_CLIENT_ID=7644a895f19b4a9d8d97b9738b899476
set SPOTIPY_CLIENT_SECRET=YourClientSecret
set SPOTIPY_REDIRECT_URI=YourRedirectURI

# Run your external process
# Set environment variables using the set command
set SPOTIPY_CLIENT_ID=7644a895f19b4a9d8d97b9738b899476
set SPOTIPY_CLIENT_SECRET=YourClientSecret
set SPOTIPY_REDIRECT_URI=YourRedirectURI

wizmusic -H <your-WiZ-IP>
```

**Comment by konrad51** [comment]
Thanks for responding.OK, my system is Windows 10. I used the set command to set the environment variables.( in a regular windows command window...no powershell). I used the "set" command to list environment variables.The spotipy variables were listed when I typed "set" in the command console. I used single quotes around the variables  ie set 'SPOTIPY_REDIRECT_URI=http://localhost:8888/callback/'
( I opened command window in wizmusic directory). Results as follows:

C:\Users\schultz\AppData\Local\Programs\Python\Python39\Lib\site-packages\wizmusic>set
'SPOTIPY_CLIENT_ID=7644a895f19b4a9d8d97b9738b899476'
'SPOTIPY_CLIENT_SECRET=3fac05dd9f3a4f41aca38b6d5d6284ad'
'SPOTIPY_REDIRECT_URI=http://localhost:8888/callback/'


C:\Users\schultz\AppData\Local\Programs\Python\Python39\Lib\site-packages\wizmusic>wizmusic
Missing envs: {'SPOTIPY_CLIENT_ID', 'SPOTIPY_CLIENT_SECRET', 'SPOTIPY_REDIRECT_URI'}

If set without single quotes I get:

C:\Users\schultz\AppData\Local\Programs\Python\Python39\Lib\site-packages\wizmusic>set
SPOTIPY_CLIENT_ID=7644a895f19b4a9d8d97b9738b899476
SPOTIPY_CLIENT_SECRET=3fac05dd9f3a4f41aca38b6d5d6284ad
SPOTIPY_REDIRECT_URI=http://localhost:8888/callback/

C:\Users\schultz\AppData\Local\Programs\Python\Python39\Lib\site-packages\wizmusic>wizmusic
Traceback (most recent call last):
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\schultz\AppData\Local\Programs\Python\Python39\Scripts\wizmusic.exe\__main__.py", line 4, in <module>
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\site-packages\wizmusic\__init__.py", line 1, in <module>
    from .client import Client
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\site-packages\wizmusic\client.py", line 11, in <module>
    from .player import spotify
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\site-packages\wizmusic\player.py", line 17, in <module>
    oauth2 = SpotifyOAuth(
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\site-packages\spotipy\oauth2.py", line 332, in __init__
    self.client_id = client_id
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\site-packages\spotipy\oauth2.py", line 94, in client_id
    self._client_id = _ensure_value(val, "client_id")
  File "c:\users\schultz\appdata\local\programs\python\python39\lib\site-packages\spotipy\oauth2.py", line 70, in _ensure_value
    raise SpotifyOauthError(msg)
spotipy.oauth2.SpotifyOauthError: No client_id. Pass it or set a 7644a895f19b4a9d8d97b9738b899476 environment variable.

I am trying really hard to get this to work. Does this even work on Windows? If so, please tell me what I am doing wrong. It seems to be something to do with setting the environment variables. A really detailed explanation (step-by-step) with examples or an alternative method of setting the environment variables would be really helpful. I think I would really enjoy this program if I could only get it to work .Thank you very much

**Comment by redraw** [comment]
Mm looks weird. You could try installing Ubuntu on Windows using WSL.
Following this tutorial https://youtu.be/7-a1A5ETeyk

And then follow the README installation steps inside the Ubuntu box

**Comment by konrad51** [comment]
Installed ubuntu as per video, installed wizmusic ...still doesn't work . Got wizbulb timeout. Too bad it does'nt work on Windows. Wish I could figure out the environment variable problem. I appreciate the time and trouble you took to try to help me. Thank you.

**Comment by redraw** [comment]
Great! seems like the envs are ok. Did it authorized with your spotify app
the first time it run? Are you passing your wiz ip? Like this

wizmusic -H <your-wiz-bulb-ip>

The easiest way to find the Wiz ip is by using the Fing app in your phone,
it will run a scan in your network and list all your network devices with a
friendly name

**Comment by konrad51** [comment]
Much thanks for the help. Did not really get anywhere with this . Don't really want to install gigabytes of software to try to get one program to work (and another OS). Was hoping for a work-around to get it to work on Windows  since it seems the problem was getting the program to recognize the env variables. Appreciate the help, thanks.

**Comment by redraw** [comment]
Yeah I understand. You might try setting them as system env variables.
These are for some Oracle ones, but add the SPOTIPY ones instead.

https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html

Once your envs are set correctly, if you receive wiz timeout, you might
wanna check if the Wiz IP is ok.
